version: '3'
volumes:
  database_data:
  fivem_data:
services:
  fivem:
    image: altshiftzero/fivem:latest
    ports:
      - 40120:40120
      - "30120:30120/tcp"
      - "30120:30120/udp"
    volumes:
      - fivem_data:/opt/FiveM/txData
    links:
      - database
  database:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ***CHANGEME***
    volumes:
      - database_data:/var/lib/mysql
